#!/bin/sh

# Set the colorscheme using pywal and the wallpaper using feh
wal_tile() {

  # Check if the input is valid
  if [ $# -eq 0 ]; then
    echo "Error: No input provided"
    return 1
  fi

  # Ask the user to choose a background fill mode
  echo "Choose a background fill mode:
  - center,
  - fill,
  - max,
  - scale,
  - tile"

  echo "Enter the fill mode: "
  read -r FILL_MODE

  # Run the wal command with error handling
  if ! wal -n --backend modern-colorthief -i "$@" --contrast 1.3 --saturate 0.4 --cols16 -o "$HOME/Scripts/gendunstrc"; then

    echo "Error: Failed to run wal command"
    return 1
  fi

  # Get the wallpaper file path
  wallpaper_file="${HOME}/.cache/wal/wal"

  # Check if the wallpaper file exists and is readable
  if [ ! -f "${wallpaper_file}" ] || [ ! -r "${wallpaper_file}" ]; then
    echo "Error: Wallpaper file not found or not readable"
    return 1
  fi

  # Run the feh command with error handling
  if ! feh --bg-"${FILL_MODE}" "$(cat "${wallpaper_file}")"; then
    echo "Error: Failed to run feh command"
    return 1
  fi
}
wal_tile "$@"
# Launch the borders and betterlockscreen
# launch-borders & 

# Run betterlockscreen with the new wallpaper
betterlockscreen -u "$(cat "$wallpaper_file")" --fx blur
