#!/bin/sh

wal_tile() {
  # If a new wallpaper is provided
  if [ $# -gt 0 ]; then
    wal -n --backend modern-colorthief -i "$@" --contrast 1.3 --saturate 0.4 --cols16 -o "$HOME/Scripts/gendunstrc"
  else
    wal -R
  fi

  # Path to the current wal wallpaper
  wallpaper_file="${HOME}/.cache/wal/wal"

  



  if [ ! -f "$wallpaper_file" ] || [ ! -r "$wallpaper_file" ]; then
    echo "Error: Wallpaper file not found or not readable"
    return 1
  fi

  # Copy the actual wallpaper file to wal.jpg
  cp "$(cat "$wallpaper_file")" "${HOME}/.cache/wal/wal.jpg"

  # Set the wallpaper for swaybg
  swaybg -i "${HOME}/.cache/wal/wal.jpg" -m fill &

  # # Set the wallpaper for Hyprland
  # hyprctl hyprpaper set "$(cat "$wallpaper_file"),output:eDP-1,mode:fill"

  # Lock the screen with hyprlock using the current wallpaper
  hyprctl reload
}

wal_tile "$@"
